/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1_edd15;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Destroy the time
 */
public class interfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form interfazPrincipal
     */
    
    listaSimple lista;
    Nodo auxP, auxZ;
    boolean existe,existePlanta,existeZombie;
    
    
    public interfazPrincipal() {
        initComponents();
        lista=new listaSimple();
        auxP=new Nodo();
        auxZ=new Nodo();
        existe=false;
        this.existePlanta=false;
        this.existeZombie=false;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("BIENVENIDO AL JUEGO PLANTAS VRS ZOMBIES GUATEMALTECO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 410, 57);

        jButton1.setText("Eliminar Datos");
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 240, 130, 60);

        jButton2.setText("Jugador Plantas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 150, 130, 60);

        jButton3.setText("Jugador Zombies");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 150, 140, 60);

        jButton4.setText("Comenzar!");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 350, 100, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String tipo="plantas";
        verificarTipo(tipo);       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String tipo="Zombies";
        verificarTipo(tipo);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(this.existePlanta==true)
        {
            interfazSecundaria is=new interfazSecundaria();
            this.existePlanta=false;
            
        }else if(this.existePlanta==false && this.existeZombie==true) //significa que ya existe planta y podemos proceder a zombies
        {
            interfazSecundaria is=new interfazSecundaria();
            
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Deberá agregar plantas primero que zombies","Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void verificarTipo(String tipo) { 
      
      try
      {
        if(tipo.equalsIgnoreCase("plantas"))
        {
            //Cúal es el nombre de su Jugador para plantas?, Cuántos personajes agregará?, Desea información adicional?
            String resNombre= (String)JOptionPane.showInputDialog("Ingrese el nombre del jugador para Plantas:\n");
            String resCantidad= (String) JOptionPane.showInputDialog("¿Cuántos personajes agregará?:\n");
            String infoAdicional=(String) JOptionPane.showInputDialog("¿Desea información Adicional?:\n");
            
            if(infoAdicional==null) //Verificar sí existe infoAdicional
            {
            auxP=lista.crearJugador(resNombre, tipo, Integer.parseInt(resCantidad)); //aux me servirá para recorrer la lista
            lista.recorrerLista(auxP); //recorrer, generar.dot,ejecutar comando, mostrar la imagen en labels
            }
            
            this.existe=true;
            this.existePlanta=true;
            
        }
         if(this.existe==true)
         {
           if(tipo.equalsIgnoreCase("zombies"))
            {
            String resNombre= (String)JOptionPane.showInputDialog("Ingrese el nombre del jugador para Zombies:\n");
            String resCantidad= (String) JOptionPane.showInputDialog("¿Cuántos personajes agregará?:\n");
            String infoAdicional=(String) JOptionPane.showInputDialog("¿Desea información Adicional?:\n");
            
            if(infoAdicional==null)
            {
            auxZ=lista.crearJugador(resNombre, tipo, Integer.parseInt(resCantidad));
            lista.recorrerLista(auxZ);
            }
            this.existe=false;
            this.existeZombie=true;
          }
         }else
         {
             JOptionPane.showMessageDialog(this, "Deberá crear un Jugador para plantas antes de crear el de jugador de zombies.","Error", JOptionPane.ERROR_MESSAGE);//Deberá crear un Jugador para plantas antes de crear el de zombies.
         }
      }catch(Exception io)
      {
          System.out.println(io.getMessage());
      }
        
    }
    
}
